import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LeftSidebarView from './LeftSidebarView'
import RightSidebarView from './RightSidebarView'
import Providers from '@/providers/UiProvider'
import { Modal } from '@/components/Modal'
import ModalManager from '@/components/ModalManager'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <body className={`${inter.className} layout`}>
        <aside className="sidebar left-sidebar">
          <LeftSidebarView />
        </aside>
        <main className="main-content">{children}</main>
        <aside className="sidebar right-sidebar">
          <RightSidebarView />
        </aside>
      </body>
    </html>
  )
}
