import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import LeftSidebarView from './LeftSidebarView'
import RightSidebarView from './RightSidebarView'
import SessionProviderWrapper from '@/providers/SessionProviderWrapper'
import SessionProviderConsumer from '@/providers/SessionProviderConsumer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} layout`}>
        <SessionProviderConsumer>
          <aside className="sidebar left-sidebar">
            <LeftSidebarView />
          </aside>
          <main className="main-content">{children}</main>
          <aside className="sidebar right-sidebar">
            <RightSidebarView />
          </aside>
        </SessionProviderConsumer>
      </body>
    </html>
  )
}
